/*
 * File: app/store/UserStore.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.store.UserStore', {
    extend: 'Ext.data.Store',

    requires: [
        'App.model.UserModel',
        'Ext.data.proxy.Direct',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'App.model.UserModel',
            storeId: 'UserSotore',
            proxy: {
                type: 'direct',
                api: {
                    read: 'Remote.User.Read',
                    create: 'Remote.User.Create',
                    update: 'Remote.User.Update',
                    destroy: 'Remote.User.Destroy'
                },
                reader: {
                    type: 'json',
                    root: 'data'
                }
            }
        }, cfg)]);
    }
});