/**
 * GaiaEHR (Electronic Health Records)
 * Copyright (C) 2013 Certun, LLC.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

Ext.define('App.view.Viewport', {
    extend: 'Ext.Viewport',
    // app settings
    requires: window.requires, // array is defined on _app.php
    user: window.user, // array defined on _app.php
    version: window.version, // string defined on _app.php
    minWidthToFullMode: 1585, // full mode = nav expanded
    currency: globals['gbl_currency_symbol'], // currency used

	patientImage:'/9j/4ROkRXhpZgAATU0AKgAAAAgADAEAAAMAAAABAGQAAAEBAAMAAAABAGQAAAECAAMAAAADAAAAngEGAAMAAAABAAIAAAESAAMAAAABAAEAAAEVAAMAAAABAAMAAAEaAAUAAAABAAAApAEbAAUAAAABAAAArAEoAAMAAAABAAIAAAExAAIAAAAeAAAAtAEyAAIAAAAUAAAA0odpAAQAAAABAAAA6AAAASAACAAIAAgACvzaAAAnEAAK/NoAACcQQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykAMjAxMjoxMToxOSAyMzoyNjo0NAAAAAAEkAAABwAAAAQwMjIxoAEAAwAAAAEAAQAAoAIABAAAAAEAAABkoAMABAAAAAEAAABkAAAAAAAAAAYBAwADAAAAAQAGAAABGgAFAAAAAQAAAW4BGwAFAAAAAQAAAXYBKAADAAAAAQACAAACAQAEAAAAAQAAAX4CAgAEAAAAAQAAEh4AAAAAAAAASAAAAAEAAABIAAAAAf/Y/+IMWElDQ19QUk9GSUxFAAEBAAAMSExpbm8CEAAAbW50clJHQiBYWVogB84AAgAJAAYAMQAAYWNzcE1TRlQAAAAASUVDIHNSR0IAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1IUCAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARY3BydAAAAVAAAAAzZGVzYwAAAYQAAABsd3RwdAAAAfAAAAAUYmtwdAAAAgQAAAAUclhZWgAAAhgAAAAUZ1hZWgAAAiwAAAAUYlhZWgAAAkAAAAAUZG1uZAAAAlQAAABwZG1kZAAAAsQAAACIdnVlZAAAA0wAAACGdmlldwAAA9QAAAAkbHVtaQAAA/gAAAAUbWVhcwAABAwAAAAkdGVjaAAABDAAAAAMclRSQwAABDwAAAgMZ1RSQwAABDwAAAgMYlRSQwAABDwAAAgMdGV4dAAAAABDb3B5cmlnaHQgKGMpIDE5OTggSGV3bGV0dC1QYWNrYXJkIENvbXBhbnkAAGRlc2MAAAAAAAAAEnNSR0IgSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAADzUQABAAAAARbMWFlaIAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9kZXNjAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMuY2gAAAAAAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMuY2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRlc2MAAAAAAAAALFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAACxSZWZlcmVuY2UgVmlld2luZyBDb25kaXRpb24gaW4gSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2aWV3AAAAAAATpP4AFF8uABDPFAAD7cwABBMLAANcngAAAAFYWVogAAAAAABMCVYAUAAAAFcf521lYXMAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAKPAAAAAnNpZyAAAAAAQ1JUIGN1cnYAAAAAAAAEAAAAAAUACgAPABQAGQAeACMAKAAtADIANwA7AEAARQBKAE8AVABZAF4AYwBoAG0AcgB3AHwAgQCGAIsAkACVAJoAnwCkAKkArgCyALcAvADBAMYAywDQANUA2wDgAOUA6wDwAPYA+wEBAQcBDQETARkBHwElASsBMgE4AT4BRQFMAVIBWQFgAWcBbgF1AXwBgwGLAZIBmgGhAakBsQG5AcEByQHRAdkB4QHpAfIB+gIDAgwCFAIdAiYCLwI4AkECSwJUAl0CZwJxAnoChAKOApgCogKsArYCwQLLAtUC4ALrAvUDAAMLAxYDIQMtAzgDQwNPA1oDZgNyA34DigOWA6IDrgO6A8cD0wPgA+wD+QQGBBMEIAQtBDsESARVBGMEcQR+BIwEmgSoBLYExATTBOEE8AT+BQ0FHAUrBToFSQVYBWcFdwWGBZYFpgW1BcUF1QXlBfYGBgYWBicGNwZIBlkGagZ7BowGnQavBsAG0QbjBvUHBwcZBysHPQdPB2EHdAeGB5kHrAe/B9IH5Qf4CAsIHwgyCEYIWghuCIIIlgiqCL4I0gjnCPsJEAklCToJTwlkCXkJjwmkCboJzwnlCfsKEQonCj0KVApqCoEKmAquCsUK3ArzCwsLIgs5C1ELaQuAC5gLsAvIC+EL+QwSDCoMQwxcDHUMjgynDMAM2QzzDQ0NJg1ADVoNdA2ODakNww3eDfgOEw4uDkkOZA5/DpsOtg7SDu4PCQ8lD0EPXg96D5YPsw/PD+wQCRAmEEMQYRB+EJsQuRDXEPURExExEU8RbRGMEaoRyRHoEgcSJhJFEmQShBKjEsMS4xMDEyMTQxNjE4MTpBPFE+UUBhQnFEkUahSLFK0UzhTwFRIVNBVWFXgVmxW9FeAWAxYmFkkWbBaPFrIW1hb6Fx0XQRdlF4kXrhfSF/cYGxhAGGUYihivGNUY+hkgGUUZaxmRGbcZ3RoEGioaURp3Gp4axRrsGxQbOxtjG4obshvaHAIcKhxSHHscoxzMHPUdHh1HHXAdmR3DHeweFh5AHmoelB6+HukfEx8+H2kflB+/H+ogFSBBIGwgmCDEIPAhHCFIIXUhoSHOIfsiJyJVIoIiryLdIwojOCNmI5QjwiPwJB8kTSR8JKsk2iUJJTglaCWXJccl9yYnJlcmhya3JugnGCdJJ3onqyfcKA0oPyhxKKIo1CkGKTgpaymdKdAqAio1KmgqmyrPKwIrNitpK50r0SwFLDksbiyiLNctDC1BLXYtqy3hLhYuTC6CLrcu7i8kL1ovkS/HL/4wNTBsMKQw2zESMUoxgjG6MfIyKjJjMpsy1DMNM0YzfzO4M/E0KzRlNJ402DUTNU01hzXCNf02NzZyNq426TckN2A3nDfXOBQ4UDiMOMg5BTlCOX85vDn5OjY6dDqyOu87LTtrO6o76DwnPGU8pDzjPSI9YT2hPeA+ID5gPqA+4D8hP2E/oj/iQCNAZECmQOdBKUFqQaxB7kIwQnJCtUL3QzpDfUPARANER0SKRM5FEkVVRZpF3kYiRmdGq0bwRzVHe0fASAVIS0iRSNdJHUljSalJ8Eo3Sn1KxEsMS1NLmkviTCpMcky6TQJNSk2TTdxOJU5uTrdPAE9JT5NP3VAnUHFQu1EGUVBRm1HmUjFSfFLHUxNTX1OqU/ZUQlSPVNtVKFV1VcJWD1ZcVqlW91dEV5JX4FgvWH1Yy1kaWWlZuFoHWlZaplr1W0VblVvlXDVchlzWXSddeF3JXhpebF69Xw9fYV+zYAVgV2CqYPxhT2GiYfViSWKcYvBjQ2OXY+tkQGSUZOllPWWSZedmPWaSZuhnPWeTZ+loP2iWaOxpQ2maafFqSGqfavdrT2una/9sV2yvbQhtYG25bhJua27Ebx5veG/RcCtwhnDgcTpxlXHwcktypnMBc11zuHQUdHB0zHUodYV14XY+dpt2+HdWd7N4EXhueMx5KnmJeed6RnqlewR7Y3vCfCF8gXzhfUF9oX4BfmJ+wn8jf4R/5YBHgKiBCoFrgc2CMIKSgvSDV4O6hB2EgITjhUeFq4YOhnKG14c7h5+IBIhpiM6JM4mZif6KZIrKizCLlov8jGOMyo0xjZiN/45mjs6PNo+ekAaQbpDWkT+RqJIRknqS45NNk7aUIJSKlPSVX5XJljSWn5cKl3WX4JhMmLiZJJmQmfyaaJrVm0Kbr5wcnImc951kndKeQJ6unx2fi5/6oGmg2KFHobaiJqKWowajdqPmpFakx6U4pammGqaLpv2nbqfgqFKoxKk3qamqHKqPqwKrdavprFys0K1ErbiuLa6hrxavi7AAsHWw6rFgsdayS7LCszizrrQltJy1E7WKtgG2ebbwt2i34LhZuNG5SrnCuju6tbsuu6e8IbybvRW9j74KvoS+/796v/XAcMDswWfB48JfwtvDWMPUxFHEzsVLxcjGRsbDx0HHv8g9yLzJOsm5yjjKt8s2y7bMNcy1zTXNtc42zrbPN8+40DnQutE80b7SP9LB00TTxtRJ1MvVTtXR1lXW2Ndc1+DYZNjo2WzZ8dp22vvbgNwF3IrdEN2W3hzeot8p36/gNuC94UThzOJT4tvjY+Pr5HPk/OWE5g3mlucf56noMui86Ubp0Opb6uXrcOv77IbtEe2c7ijutO9A78zwWPDl8XLx//KM8xnzp/Q09ML1UPXe9m32+/eK+Bn4qPk4+cf6V/rn+3f8B/yY/Sn9uv5L/tz/bf///+0ADEFkb2JlX0NNAAH/7gAOQWRvYmUAZIAAAAAB/9sAhAAMCAgICQgMCQkMEQsKCxEVDwwMDxUYExMVExMYEQwMDAwMDBEMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAQ0LCw0ODRAODhAUDg4OFBQODg4OFBEMDAwMDBERDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCABkAGQDASIAAhEBAxEB/90ABAAH/8QBPwAAAQUBAQEBAQEAAAAAAAAAAwABAgQFBgcICQoLAQABBQEBAQEBAQAAAAAAAAABAAIDBAUGBwgJCgsQAAEEAQMCBAIFBwYIBQMMMwEAAhEDBCESMQVBUWETInGBMgYUkaGxQiMkFVLBYjM0coLRQwclklPw4fFjczUWorKDJkSTVGRFwqN0NhfSVeJl8rOEw9N14/NGJ5SkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2N0dXZ3eHl6e3x9fn9xEAAgIBAgQEAwQFBgcHBgU1AQACEQMhMRIEQVFhcSITBTKBkRShsUIjwVLR8DMkYuFygpJDUxVjczTxJQYWorKDByY1wtJEk1SjF2RFVTZ0ZeLys4TD03Xj80aUpIW0lcTU5PSltcXV5fVWZnaGlqa2xtbm9ic3R1dnd4eXp7fH/9oADAMBAAIRAxEAPwD1VJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJT/9D1VJJJJSkkkklKWXn/AFm6JgWGm/JabhzVWC9wP8r092z+2sb69/WK7p9DOn4byzIyWl1ljeW1/R9v7rrXLhMS6qlpseNz3eKSn0ln126CTFj7Kh+8+sx/0N62cXMxc2oXYlrL6j+cwgj4LyQ9RqsG1zRBS6T1nJ6L1AZOK4mqR6tU+17O7Xf98ckp9hSQsbIqyserJpO6q5oew+ThuCKkpSSSSSlJJJJKf//R9VSSSSUpJJJJT5P9dr3XfWXLB4q2Vt+AY0/9U5Ykrc+u9Jq+s2UTxZsePmxo/wCqasJJSkikkUkvqn1Fvdd9W8YOMmpz6x8A4lv/AFS6BYH1FpNX1axiebC9/wAi9wH/AEWrfSQpJJJJSkkkklP/0vVUkkklKSSSSU+e/wCMvCLM3EzgPbbWanHzYd7f+jYuNXsH1k6TX1bpF+MRNjWmyg+FjRLP876C8fCSlJQ5zg1olzjAA7kpLo/qH0lnUOs+vcN1WE0Wx2L5in/0p/YSS+j9LxPsXTcXE70VMYfiAN3/AElaSSSQpJJJJS3dJOkkp//T9UTpJJKUkh3ZFFDN99jKmfvPcGj73LGzfrp0LFkMtdlWD8yhu7/wQ7av+mkp3CQBJ4XiWWKxl3ioh1YsfsI4Ldx2rput/W3q/Va3Y+PX9ixH6P1l7h+69/7v8li5d9bWaTJSUjXe/wCLIVinPMj1S6uW99oD4P8AnFcGInXhX+m5GdgZLcvp9uy1unkR3Y9v57UlPsiS5Dp31/rIDOqYr6X97avew+ez+cZ/4Iugw+u9HzY+zZdb3H8wna7/ALbs2vSU30kkklKSSSSU/wD/1O1699cendI/QsH2rLI0qYYDf+NfrtXL5P1p+sOdJdeMOo8MpG0x/wAY7dZ/0lyvquLt7jucTJJ1Mqb8q1/LvuSU6dtlLnb8i119ndz3Fx+9yE/PpZpW0LNLieSmlJTZtzLLPIKuSTymlKUkrqTLXsMgqEpJKb1XUSBDxKOMjDt+k0BZSUpIehxc/PxYOBm2VAcM3S3/ALbfuYtjB+v+ZjWNq6vQLazp69Ptd8XV/Qf/AGfTXENte3gkKVmQ+xoa8yAkp9k/a/Tf2f8AtL12/ZNu/wBTy4+j9Lfu9uxJeOfbMj7N9k3n0N2/Z2lJJT//1edG2O8pwuLSSS9qm1XFpJKe01TrikklPa6parikklPa6p1xKSSntdUy4tJJT2uqS4pJJT//2f/tG4ZQaG90b3Nob3AgMy4wADhCSU0EBAAAAAAADxwBWgADGyVHHAIAAAIAAAA4QklNBCUAAAAAABDNz/p9qMe+CQVwdq6vBcNOOEJJTQQ6AAAAAADlAAAAEAAAAAEAAAAAAAtwcmludE91dHB1dAAAAAUAAAAAUHN0U2Jvb2wBAAAAAEludGVlbnVtAAAAAEludGUAAAAAQ2xybQAAAA9wcmludFNpeHRlZW5CaXRib29sAAAAAAtwcmludGVyTmFtZVRFWFQAAAABAAAAAAAPcHJpbnRQcm9vZlNldHVwT2JqYwAAAAwAUAByAG8AbwBmACAAUwBlAHQAdQBwAAAAAAAKcHJvb2ZTZXR1cAAAAAEAAAAAQmx0bmVudW0AAAAMYnVpbHRpblByb29mAAAACXByb29mQ01ZSwA4QklNBDsAAAAAAi0AAAAQAAAAAQAAAAAAEnByaW50T3V0cHV0T3B0aW9ucwAAABcAAAAAQ3B0bmJvb2wAAAAAAENsYnJib29sAAAAAABSZ3NNYm9vbAAAAAAAQ3JuQ2Jvb2wAAAAAAENudENib29sAAAAAABMYmxzYm9vbAAAAAAATmd0dmJvb2wAAAAAAEVtbERib29sAAAAAABJbnRyYm9vbAAAAAAAQmNrZ09iamMAAAABAAAAAAAAUkdCQwAAAAMAAAAAUmQgIGRvdWJAb+AAAAAAAAAAAABHcm4gZG91YkBv4AAAAAAAAAAAAEJsICBkb3ViQG/gAAAAAAAAAAAAQnJkVFVudEYjUmx0AAAAAAAAAAAAAAAAQmxkIFVudEYjUmx0AAAAAAAAAAAAAAAAUnNsdFVudEYjUHhsQFIAk4AAAAAAAAAKdmVjdG9yRGF0YWJvb2wBAAAAAFBnUHNlbnVtAAAAAFBnUHMAAAAAUGdQQwAAAABMZWZ0VW50RiNSbHQAAAAAAAAAAAAAAABUb3AgVW50RiNSbHQAAAAAAAAAAAAAAABTY2wgVW50RiNQcmNAWQAAAAAAAAAAABBjcm9wV2hlblByaW50aW5nYm9vbAAAAAAOY3JvcFJlY3RCb3R0b21sb25nAAAAAAAAAAxjcm9wUmVjdExlZnRsb25nAAAAAAAAAA1jcm9wUmVjdFJpZ2h0bG9uZwAAAAAAAAALY3JvcFJlY3RUb3Bsb25nAAAAAAA4QklNA+0AAAAAABAASAJOAAEAAQBIAk4AAQABOEJJTQQmAAAAAAAOAAAAAAAAAAAAAD+AAAA4QklNA/IAAAAAAAoAAP///////wAAOEJJTQQNAAAAAAAEAAAAHjhCSU0EGQAAAAAABAAAAB44QklNA/MAAAAAAAkAAAAAAAAAAAEAOEJJTScQAAAAAAAKAAEAAAAAAAAAAThCSU0D9QAAAAAASAAvZmYAAQBsZmYABgAAAAAAAQAvZmYAAQChmZoABgAAAAAAAQAyAAAAAQBaAAAABgAAAAAAAQA1AAAAAQAtAAAABgAAAAAAAThCSU0D+AAAAAAAcAAA/////////////////////////////wPoAAAAAP////////////////////////////8D6AAAAAD/////////////////////////////A+gAAAAA/////////////////////////////wPoAAA4QklNBAAAAAAAAAIAADhCSU0EAgAAAAAAAgAAOEJJTQQwAAAAAAABAQA4QklNBC0AAAAAAAYAAQAAAAQ4QklNBAgAAAAAABAAAAABAAACQAAAAkAAAAAAOEJJTQQeAAAAAAAEAAAAADhCSU0EGgAAAAADUQAAAAYAAAAAAAAAAAAAAGQAAABkAAAADgBwAGEAdABpAGUAbgB0AFAAaABvAHQAbwBJAGQAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAGQAAABkAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAEAAAAAAABudWxsAAAAAgAAAAZib3VuZHNPYmpjAAAAAQAAAAAAAFJjdDEAAAAEAAAAAFRvcCBsb25nAAAAAAAAAABMZWZ0bG9uZwAAAAAAAAAAQnRvbWxvbmcAAABkAAAAAFJnaHRsb25nAAAAZAAAAAZzbGljZXNWbExzAAAAAU9iamMAAAABAAAAAAAFc2xpY2UAAAASAAAAB3NsaWNlSURsb25nAAAAAAAAAAdncm91cElEbG9uZwAAAAAAAAAGb3JpZ2luZW51bQAAAAxFU2xpY2VPcmlnaW4AAAANYXV0b0dlbmVyYXRlZAAAAABUeXBlZW51bQAAAApFU2xpY2VUeXBlAAAAAEltZyAAAAAGYm91bmRzT2JqYwAAAAEAAAAAAABSY3QxAAAABAAAAABUb3AgbG9uZwAAAAAAAAAATGVmdGxvbmcAAAAAAAAAAEJ0b21sb25nAAAAZAAAAABSZ2h0bG9uZwAAAGQAAAADdXJsVEVYVAAAAAEAAAAAAABudWxsVEVYVAAAAAEAAAAAAABNc2dlVEVYVAAAAAEAAAAAAAZhbHRUYWdURVhUAAAAAQAAAAAADmNlbGxUZXh0SXNIVE1MYm9vbAEAAAAIY2VsbFRleHRURVhUAAAAAQAAAAAACWhvcnpBbGlnbmVudW0AAAAPRVNsaWNlSG9yekFsaWduAAAAB2RlZmF1bHQAAAAJdmVydEFsaWduZW51bQAAAA9FU2xpY2VWZXJ0QWxpZ24AAAAHZGVmYXVsdAAAAAtiZ0NvbG9yVHlwZWVudW0AAAARRVNsaWNlQkdDb2xvclR5cGUAAAAATm9uZQAAAAl0b3BPdXRzZXRsb25nAAAAAAAAAApsZWZ0T3V0c2V0bG9uZwAAAAAAAAAMYm90dG9tT3V0c2V0bG9uZwAAAAAAAAALcmlnaHRPdXRzZXRsb25nAAAAAAA4QklNBCgAAAAAAAwAAAACP/AAAAAAAAA4QklNBBQAAAAAAAQAAAAEOEJJTQQMAAAAABI6AAAAAQAAAGQAAABkAAABLAAAdTAAABIeABgAAf/Y/+IMWElDQ19QUk9GSUxFAAEBAAAMSExpbm8CEAAAbW50clJHQiBYWVogB84AAgAJAAYAMQAAYWNzcE1TRlQAAAAASUVDIHNSR0IAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1IUCAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARY3BydAAAAVAAAAAzZGVzYwAAAYQAAABsd3RwdAAAAfAAAAAUYmtwdAAAAgQAAAAUclhZWgAAAhgAAAAUZ1hZWgAAAiwAAAAUYlhZWgAAAkAAAAAUZG1uZAAAAlQAAABwZG1kZAAAAsQAAACIdnVlZAAAA0wAAACGdmlldwAAA9QAAAAkbHVtaQAAA/gAAAAUbWVhcwAABAwAAAAkdGVjaAAABDAAAAAMclRSQwAABDwAAAgMZ1RSQwAABDwAAAgMYlRSQwAABDwAAAgMdGV4dAAAAABDb3B5cmlnaHQgKGMpIDE5OTggSGV3bGV0dC1QYWNrYXJkIENvbXBhbnkAAGRlc2MAAAAAAAAAEnNSR0IgSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAADzUQABAAAAARbMWFlaIAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9kZXNjAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMuY2gAAAAAAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMuY2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRlc2MAAAAAAAAALFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAACxSZWZlcmVuY2UgVmlld2luZyBDb25kaXRpb24gaW4gSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2aWV3AAAAAAATpP4AFF8uABDPFAAD7cwABBMLAANcngAAAAFYWVogAAAAAABMCVYAUAAAAFcf521lYXMAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAKPAAAAAnNpZyAAAAAAQ1JUIGN1cnYAAAAAAAAEAAAAAAUACgAPABQAGQAeACMAKAAtADIANwA7AEAARQBKAE8AVABZAF4AYwBoAG0AcgB3AHwAgQCGAIsAkACVAJoAnwCkAKkArgCyALcAvADBAMYAywDQANUA2wDgAOUA6wDwAPYA+wEBAQcBDQETARkBHwElASsBMgE4AT4BRQFMAVIBWQFgAWcBbgF1AXwBgwGLAZIBmgGhAakBsQG5AcEByQHRAdkB4QHpAfIB+gIDAgwCFAIdAiYCLwI4AkECSwJUAl0CZwJxAnoChAKOApgCogKsArYCwQLLAtUC4ALrAvUDAAMLAxYDIQMtAzgDQwNPA1oDZgNyA34DigOWA6IDrgO6A8cD0wPgA+wD+QQGBBMEIAQtBDsESARVBGMEcQR+BIwEmgSoBLYExATTBOEE8AT+BQ0FHAUrBToFSQVYBWcFdwWGBZYFpgW1BcUF1QXlBfYGBgYWBicGNwZIBlkGagZ7BowGnQavBsAG0QbjBvUHBwcZBysHPQdPB2EHdAeGB5kHrAe/B9IH5Qf4CAsIHwgyCEYIWghuCIIIlgiqCL4I0gjnCPsJEAklCToJTwlkCXkJjwmkCboJzwnlCfsKEQonCj0KVApqCoEKmAquCsUK3ArzCwsLIgs5C1ELaQuAC5gLsAvIC+EL+QwSDCoMQwxcDHUMjgynDMAM2QzzDQ0NJg1ADVoNdA2ODakNww3eDfgOEw4uDkkOZA5/DpsOtg7SDu4PCQ8lD0EPXg96D5YPsw/PD+wQCRAmEEMQYRB+EJsQuRDXEPURExExEU8RbRGMEaoRyRHoEgcSJhJFEmQShBKjEsMS4xMDEyMTQxNjE4MTpBPFE+UUBhQnFEkUahSLFK0UzhTwFRIVNBVWFXgVmxW9FeAWAxYmFkkWbBaPFrIW1hb6Fx0XQRdlF4kXrhfSF/cYGxhAGGUYihivGNUY+hkgGUUZaxmRGbcZ3RoEGioaURp3Gp4axRrsGxQbOxtjG4obshvaHAIcKhxSHHscoxzMHPUdHh1HHXAdmR3DHeweFh5AHmoelB6+HukfEx8+H2kflB+/H+ogFSBBIGwgmCDEIPAhHCFIIXUhoSHOIfsiJyJVIoIiryLdIwojOCNmI5QjwiPwJB8kTSR8JKsk2iUJJTglaCWXJccl9yYnJlcmhya3JugnGCdJJ3onqyfcKA0oPyhxKKIo1CkGKTgpaymdKdAqAio1KmgqmyrPKwIrNitpK50r0SwFLDksbiyiLNctDC1BLXYtqy3hLhYuTC6CLrcu7i8kL1ovkS/HL/4wNTBsMKQw2zESMUoxgjG6MfIyKjJjMpsy1DMNM0YzfzO4M/E0KzRlNJ402DUTNU01hzXCNf02NzZyNq426TckN2A3nDfXOBQ4UDiMOMg5BTlCOX85vDn5OjY6dDqyOu87LTtrO6o76DwnPGU8pDzjPSI9YT2hPeA+ID5gPqA+4D8hP2E/oj/iQCNAZECmQOdBKUFqQaxB7kIwQnJCtUL3QzpDfUPARANER0SKRM5FEkVVRZpF3kYiRmdGq0bwRzVHe0fASAVIS0iRSNdJHUljSalJ8Eo3Sn1KxEsMS1NLmkviTCpMcky6TQJNSk2TTdxOJU5uTrdPAE9JT5NP3VAnUHFQu1EGUVBRm1HmUjFSfFLHUxNTX1OqU/ZUQlSPVNtVKFV1VcJWD1ZcVqlW91dEV5JX4FgvWH1Yy1kaWWlZuFoHWlZaplr1W0VblVvlXDVchlzWXSddeF3JXhpebF69Xw9fYV+zYAVgV2CqYPxhT2GiYfViSWKcYvBjQ2OXY+tkQGSUZOllPWWSZedmPWaSZuhnPWeTZ+loP2iWaOxpQ2maafFqSGqfavdrT2una/9sV2yvbQhtYG25bhJua27Ebx5veG/RcCtwhnDgcTpxlXHwcktypnMBc11zuHQUdHB0zHUodYV14XY+dpt2+HdWd7N4EXhueMx5KnmJeed6RnqlewR7Y3vCfCF8gXzhfUF9oX4BfmJ+wn8jf4R/5YBHgKiBCoFrgc2CMIKSgvSDV4O6hB2EgITjhUeFq4YOhnKG14c7h5+IBIhpiM6JM4mZif6KZIrKizCLlov8jGOMyo0xjZiN/45mjs6PNo+ekAaQbpDWkT+RqJIRknqS45NNk7aUIJSKlPSVX5XJljSWn5cKl3WX4JhMmLiZJJmQmfyaaJrVm0Kbr5wcnImc951kndKeQJ6unx2fi5/6oGmg2KFHobaiJqKWowajdqPmpFakx6U4pammGqaLpv2nbqfgqFKoxKk3qamqHKqPqwKrdavprFys0K1ErbiuLa6hrxavi7AAsHWw6rFgsdayS7LCszizrrQltJy1E7WKtgG2ebbwt2i34LhZuNG5SrnCuju6tbsuu6e8IbybvRW9j74KvoS+/796v/XAcMDswWfB48JfwtvDWMPUxFHEzsVLxcjGRsbDx0HHv8g9yLzJOsm5yjjKt8s2y7bMNcy1zTXNtc42zrbPN8+40DnQutE80b7SP9LB00TTxtRJ1MvVTtXR1lXW2Ndc1+DYZNjo2WzZ8dp22vvbgNwF3IrdEN2W3hzeot8p36/gNuC94UThzOJT4tvjY+Pr5HPk/OWE5g3mlucf56noMui86Ubp0Opb6uXrcOv77IbtEe2c7ijutO9A78zwWPDl8XLx//KM8xnzp/Q09ML1UPXe9m32+/eK+Bn4qPk4+cf6V/rn+3f8B/yY/Sn9uv5L/tz/bf///+0ADEFkb2JlX0NNAAH/7gAOQWRvYmUAZIAAAAAB/9sAhAAMCAgICQgMCQkMEQsKCxEVDwwMDxUYExMVExMYEQwMDAwMDBEMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAQ0LCw0ODRAODhAUDg4OFBQODg4OFBEMDAwMDBERDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCABkAGQDASIAAhEBAxEB/90ABAAH/8QBPwAAAQUBAQEBAQEAAAAAAAAAAwABAgQFBgcICQoLAQABBQEBAQEBAQAAAAAAAAABAAIDBAUGBwgJCgsQAAEEAQMCBAIFBwYIBQMMMwEAAhEDBCESMQVBUWETInGBMgYUkaGxQiMkFVLBYjM0coLRQwclklPw4fFjczUWorKDJkSTVGRFwqN0NhfSVeJl8rOEw9N14/NGJ5SkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2N0dXZ3eHl6e3x9fn9xEAAgIBAgQEAwQFBgcHBgU1AQACEQMhMRIEQVFhcSITBTKBkRShsUIjwVLR8DMkYuFygpJDUxVjczTxJQYWorKDByY1wtJEk1SjF2RFVTZ0ZeLys4TD03Xj80aUpIW0lcTU5PSltcXV5fVWZnaGlqa2xtbm9ic3R1dnd4eXp7fH/9oADAMBAAIRAxEAPwD1VJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJT/9D1VJJJJSkkkklKWXn/AFm6JgWGm/JabhzVWC9wP8r092z+2sb69/WK7p9DOn4byzIyWl1ljeW1/R9v7rrXLhMS6qlpseNz3eKSn0ln126CTFj7Kh+8+sx/0N62cXMxc2oXYlrL6j+cwgj4LyQ9RqsG1zRBS6T1nJ6L1AZOK4mqR6tU+17O7Xf98ckp9hSQsbIqyserJpO6q5oew+ThuCKkpSSSSSlJJJJKf//R9VSSSSUpJJJJT5P9dr3XfWXLB4q2Vt+AY0/9U5Ykrc+u9Jq+s2UTxZsePmxo/wCqasJJSkikkUkvqn1Fvdd9W8YOMmpz6x8A4lv/AFS6BYH1FpNX1axiebC9/wAi9wH/AEWrfSQpJJJJSkkkklP/0vVUkkklKSSSSU+e/wCMvCLM3EzgPbbWanHzYd7f+jYuNXsH1k6TX1bpF+MRNjWmyg+FjRLP876C8fCSlJQ5zg1olzjAA7kpLo/qH0lnUOs+vcN1WE0Wx2L5in/0p/YSS+j9LxPsXTcXE70VMYfiAN3/AElaSSSQpJJJJS3dJOkkp//T9UTpJJKUkh3ZFFDN99jKmfvPcGj73LGzfrp0LFkMtdlWD8yhu7/wQ7av+mkp3CQBJ4XiWWKxl3ioh1YsfsI4Ldx2rput/W3q/Va3Y+PX9ixH6P1l7h+69/7v8li5d9bWaTJSUjXe/wCLIVinPMj1S6uW99oD4P8AnFcGInXhX+m5GdgZLcvp9uy1unkR3Y9v57UlPsiS5Dp31/rIDOqYr6X97avew+ez+cZ/4Iugw+u9HzY+zZdb3H8wna7/ALbs2vSU30kkklKSSSSU/wD/1O1699cendI/QsH2rLI0qYYDf+NfrtXL5P1p+sOdJdeMOo8MpG0x/wAY7dZ/0lyvquLt7jucTJJ1Mqb8q1/LvuSU6dtlLnb8i119ndz3Fx+9yE/PpZpW0LNLieSmlJTZtzLLPIKuSTymlKUkrqTLXsMgqEpJKb1XUSBDxKOMjDt+k0BZSUpIehxc/PxYOBm2VAcM3S3/ALbfuYtjB+v+ZjWNq6vQLazp69Ptd8XV/Qf/AGfTXENte3gkKVmQ+xoa8yAkp9k/a/Tf2f8AtL12/ZNu/wBTy4+j9Lfu9uxJeOfbMj7N9k3n0N2/Z2lJJT//1edG2O8pwuLSSS9qm1XFpJKe01TrikklPa6parikklPa6p1xKSSntdUy4tJJT2uqS4pJJT//2ThCSU0EIQAAAAAAVQAAAAEBAAAADwBBAGQAbwBiAGUAIABQAGgAbwB0AG8AcwBoAG8AcAAAABMAQQBkAG8AYgBlACAAUABoAG8AdABvAHMAaABvAHAAIABDAFMANgAAAAEAOEJJTQQGAAAAAAAHAAgAAAABAQD/4Q+7aHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwYWNrZXQgYmVnaW49Iu+7vyIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/PiA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJBZG9iZSBYTVAgQ29yZSA1LjMtYzAxMSA2Ni4xNDU2NjEsIDIwMTIvMDIvMDYtMTQ6NTY6MjcgICAgICAgICI+IDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+IDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzYgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAxMi0wNC0yNFQxNjozMDoyNi0wNDowMCIgeG1wOk1vZGlmeURhdGU9IjIwMTItMTEtMTlUMjM6MjY6NDQtMDQ6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMTItMTEtMTlUMjM6MjY6NDQtMDQ6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvanBlZyIgcGhvdG9zaG9wOkxlZ2FjeUlQVENEaWdlc3Q9IjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiBwaG90b3Nob3A6SUNDUHJvZmlsZT0ic1JHQiBJRUM2MTk2Ni0yLjEiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6OUY0MEQzMUJDMjMyRTIxMUE1NzhERjExOTIzOEY2MTMiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MDczMkY4ODg3Q0FGRTExMUIxNzRGM0Y5REZEMjcyREQiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDowNzMyRjg4ODdDQUZFMTExQjE3NEYzRjlERkQyNzJERCI+IDxwaG90b3Nob3A6RG9jdW1lbnRBbmNlc3RvcnM+IDxyZGY6QmFnPiA8cmRmOmxpPnhtcC5kaWQ6MDczMkY4ODg3Q0FGRTExMUIxNzRGM0Y5REZEMjcyREQ8L3JkZjpsaT4gPC9yZGY6QmFnPiA8L3Bob3Rvc2hvcDpEb2N1bWVudEFuY2VzdG9ycz4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDowNzMyRjg4ODdDQUZFMTExQjE3NEYzRjlERkQyNzJERCIgc3RFdnQ6d2hlbj0iMjAxMi0wNC0yNFQxNjozMDoyNi0wNDowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImNvbnZlcnRlZCIgc3RFdnQ6cGFyYW1ldGVycz0iZnJvbSBpbWFnZS9wbmcgdG8gaW1hZ2UvanBlZyIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MDgzMkY4ODg3Q0FGRTExMUIxNzRGM0Y5REZEMjcyREQiIHN0RXZ0OndoZW49IjIwMTItMDYtMDVUMjI6MDg6NDAtMDQ6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDUzYgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo5RjQwRDMxQkMyMzJFMjExQTU3OERGMTE5MjM4RjYxMyIgc3RFdnQ6d2hlbj0iMjAxMi0xMS0xOVQyMzoyNjo0NC0wNDowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDw/eHBhY2tldCBlbmQ9InciPz7/4gxYSUNDX1BST0ZJTEUAAQEAAAxITGlubwIQAABtbnRyUkdCIFhZWiAHzgACAAkABgAxAABhY3NwTVNGVAAAAABJRUMgc1JHQgAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLUhQICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFjcHJ0AAABUAAAADNkZXNjAAABhAAAAGx3dHB0AAAB8AAAABRia3B0AAACBAAAABRyWFlaAAACGAAAABRnWFlaAAACLAAAABRiWFlaAAACQAAAABRkbW5kAAACVAAAAHBkbWRkAAACxAAAAIh2dWVkAAADTAAAAIZ2aWV3AAAD1AAAACRsdW1pAAAD+AAAABRtZWFzAAAEDAAAACR0ZWNoAAAEMAAAAAxyVFJDAAAEPAAACAxnVFJDAAAEPAAACAxiVFJDAAAEPAAACAx0ZXh0AAAAAENvcHlyaWdodCAoYykgMTk5OCBIZXdsZXR0LVBhY2thcmQgQ29tcGFueQAAZGVzYwAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAABJzUkdCIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAAPNRAAEAAAABFsxYWVogAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z2Rlc2MAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkZXNjAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAsUmVmZXJlbmNlIFZpZXdpbmcgQ29uZGl0aW9uIGluIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAALFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHZpZXcAAAAAABOk/gAUXy4AEM8UAAPtzAAEEwsAA1yeAAAAAVhZWiAAAAAAAEwJVgBQAAAAVx/nbWVhcwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAo8AAAACc2lnIAAAAABDUlQgY3VydgAAAAAAAAQAAAAABQAKAA8AFAAZAB4AIwAoAC0AMgA3ADsAQABFAEoATwBUAFkAXgBjAGgAbQByAHcAfACBAIYAiwCQAJUAmgCfAKQAqQCuALIAtwC8AMEAxgDLANAA1QDbAOAA5QDrAPAA9gD7AQEBBwENARMBGQEfASUBKwEyATgBPgFFAUwBUgFZAWABZwFuAXUBfAGDAYsBkgGaAaEBqQGxAbkBwQHJAdEB2QHhAekB8gH6AgMCDAIUAh0CJgIvAjgCQQJLAlQCXQJnAnECegKEAo4CmAKiAqwCtgLBAssC1QLgAusC9QMAAwsDFgMhAy0DOANDA08DWgNmA3IDfgOKA5YDogOuA7oDxwPTA+AD7AP5BAYEEwQgBC0EOwRIBFUEYwRxBH4EjASaBKgEtgTEBNME4QTwBP4FDQUcBSsFOgVJBVgFZwV3BYYFlgWmBbUFxQXVBeUF9gYGBhYGJwY3BkgGWQZqBnsGjAadBq8GwAbRBuMG9QcHBxkHKwc9B08HYQd0B4YHmQesB78H0gflB/gICwgfCDIIRghaCG4IggiWCKoIvgjSCOcI+wkQCSUJOglPCWQJeQmPCaQJugnPCeUJ+woRCicKPQpUCmoKgQqYCq4KxQrcCvMLCwsiCzkLUQtpC4ALmAuwC8gL4Qv5DBIMKgxDDFwMdQyODKcMwAzZDPMNDQ0mDUANWg10DY4NqQ3DDd4N+A4TDi4OSQ5kDn8Omw62DtIO7g8JDyUPQQ9eD3oPlg+zD88P7BAJECYQQxBhEH4QmxC5ENcQ9RETETERTxFtEYwRqhHJEegSBxImEkUSZBKEEqMSwxLjEwMTIxNDE2MTgxOkE8UT5RQGFCcUSRRqFIsUrRTOFPAVEhU0FVYVeBWbFb0V4BYDFiYWSRZsFo8WshbWFvoXHRdBF2UXiReuF9IX9xgbGEAYZRiKGK8Y1Rj6GSAZRRlrGZEZtxndGgQaKhpRGncanhrFGuwbFBs7G2MbihuyG9ocAhwqHFIcexyjHMwc9R0eHUcdcB2ZHcMd7B4WHkAeah6UHr4e6R8THz4faR+UH78f6iAVIEEgbCCYIMQg8CEcIUghdSGhIc4h+yInIlUigiKvIt0jCiM4I2YjlCPCI/AkHyRNJHwkqyTaJQklOCVoJZclxyX3JicmVyaHJrcm6CcYJ0kneierJ9woDSg/KHEooijUKQYpOClrKZ0p0CoCKjUqaCqbKs8rAis2K2krnSvRLAUsOSxuLKIs1y0MLUEtdi2rLeEuFi5MLoIuty7uLyQvWi+RL8cv/jA1MGwwpDDbMRIxSjGCMbox8jIqMmMymzLUMw0zRjN/M7gz8TQrNGU0njTYNRM1TTWHNcI1/TY3NnI2rjbpNyQ3YDecN9c4FDhQOIw4yDkFOUI5fzm8Ofk6Njp0OrI67zstO2s7qjvoPCc8ZTykPOM9Ij1hPaE94D4gPmA+oD7gPyE/YT+iP+JAI0BkQKZA50EpQWpBrEHuQjBCckK1QvdDOkN9Q8BEA0RHRIpEzkUSRVVFmkXeRiJGZ0arRvBHNUd7R8BIBUhLSJFI10kdSWNJqUnwSjdKfUrESwxLU0uaS+JMKkxyTLpNAk1KTZNN3E4lTm5Ot08AT0lPk0/dUCdQcVC7UQZRUFGbUeZSMVJ8UsdTE1NfU6pT9lRCVI9U21UoVXVVwlYPVlxWqVb3V0RXklfgWC9YfVjLWRpZaVm4WgdaVlqmWvVbRVuVW+VcNVyGXNZdJ114XcleGl5sXr1fD19hX7NgBWBXYKpg/GFPYaJh9WJJYpxi8GNDY5dj62RAZJRk6WU9ZZJl52Y9ZpJm6Gc9Z5Nn6Wg/aJZo7GlDaZpp8WpIap9q92tPa6dr/2xXbK9tCG1gbbluEm5rbsRvHm94b9FwK3CGcOBxOnGVcfByS3KmcwFzXXO4dBR0cHTMdSh1hXXhdj52m3b4d1Z3s3gReG54zHkqeYl553pGeqV7BHtje8J8IXyBfOF9QX2hfgF+Yn7CfyN/hH/lgEeAqIEKgWuBzYIwgpKC9INXg7qEHYSAhOOFR4Wrhg6GcobXhzuHn4gEiGmIzokziZmJ/opkisqLMIuWi/yMY4zKjTGNmI3/jmaOzo82j56QBpBukNaRP5GokhGSepLjk02TtpQglIqU9JVflcmWNJaflwqXdZfgmEyYuJkkmZCZ/JpomtWbQpuvnByciZz3nWSd0p5Anq6fHZ+Ln/qgaaDYoUehtqImopajBqN2o+akVqTHpTilqaYapoum/adup+CoUqjEqTepqaocqo+rAqt1q+msXKzQrUStuK4trqGvFq+LsACwdbDqsWCx1rJLssKzOLOutCW0nLUTtYq2AbZ5tvC3aLfguFm40blKucK6O7q1uy67p7whvJu9Fb2Pvgq+hL7/v3q/9cBwwOzBZ8Hjwl/C28NYw9TEUcTOxUvFyMZGxsPHQce/yD3IvMk6ybnKOMq3yzbLtsw1zLXNNc21zjbOts83z7jQOdC60TzRvtI/0sHTRNPG1EnUy9VO1dHWVdbY11zX4Nhk2OjZbNnx2nba+9uA3AXcit0Q3ZbeHN6i3ynfr+A24L3hROHM4lPi2+Nj4+vkc+T85YTmDeaW5x/nqegy6LzpRunQ6lvq5etw6/vshu0R7ZzuKO6070DvzPBY8OXxcvH/8ozzGfOn9DT0wvVQ9d72bfb794r4Gfio+Tj5x/pX+uf7d/wH/Jj9Kf26/kv+3P9t////7gAOQWRvYmUAZEAAAAAB/9sAhAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgICAgICAgICAgIDAwMDAwMDAwMDAQEBAQEBAQEBAQECAgECAgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwP/wAARCABkAGQDAREAAhEBAxEB/90ABAAN/8QBogAAAAYCAwEAAAAAAAAAAAAABwgGBQQJAwoCAQALAQAABgMBAQEAAAAAAAAAAAAGBQQDBwIIAQkACgsQAAIBAwQBAwMCAwMDAgYJdQECAwQRBRIGIQcTIgAIMRRBMiMVCVFCFmEkMxdScYEYYpElQ6Gx8CY0cgoZwdE1J+FTNoLxkqJEVHNFRjdHYyhVVlcassLS4vJkg3SThGWjs8PT4yk4ZvN1Kjk6SElKWFlaZ2hpanZ3eHl6hYaHiImKlJWWl5iZmqSlpqeoqaq0tba3uLm6xMXGx8jJytTV1tfY2drk5ebn6Onq9PX29/j5+hEAAgEDAgQEAwUEBAQGBgVtAQIDEQQhEgUxBgAiE0FRBzJhFHEIQoEjkRVSoWIWMwmxJMHRQ3LwF+GCNCWSUxhjRPGisiY1GVQ2RWQnCnODk0Z0wtLi8lVldVY3hIWjs8PT4/MpGpSktMTU5PSVpbXF1eX1KEdXZjh2hpamtsbW5vZnd4eXp7fH1+f3SFhoeIiYqLjI2Oj4OUlZaXmJmam5ydnp+So6SlpqeoqaqrrK2ur6/9oADAMBAAIRAxEAPwDf49+691737r3Xvfuvde9+691737r3Xvfuvde9+691737r3Xvfuvde9+691737r3Xvfuvde9+691//0N/j37r3Xvfuvde9+691737r3Xvfuvde9+691737r3Xvfuvde9+691737r3Xvfuvde9+691737r3X//R3+Pfuvde9+691737r3Xvfuvde9+690RDvj+Zb8K/jruCq2Z2D3dgqrflFK8FZsXY9Hld/bpoKqO/ko8vR7UospS7frEtzFkZ6RxcXFj7917oAsX/ADsPghUVcUG4N09i7GoZZFRc3urrLcRxCamCrJPLttNxVlPDzcvJCqqBdiPfuvdWRdV9x9V947TpN9dP9gbU7I2jWM0UWd2hmqLM0UdSqq0lFWGkleXHZGAMPJTVCxTx39SD37r3Qle/de697917r3v3Xuve/de697917r//0t/j37r3Xvfuvde9+691737r3WvZ/Pc/mG7t+NextsfGzpbcFVtvtXuHCVue3hu3EVJps5svrFaqbEQ0+Eq4XSoxmd3vk6aqgjrIyJqSjoqgxlJZYZY/dbAJNB1qXdV7t23smjqdxZenGUzuRqJmV6omaREWRgSXcszvNJd2YksxPPvfT3Qs1PyH23uOCXF5XB0v2s6NCS0K8Bhp+tvwD710x1w+JnzI7L+CvyCoezOqMxXz7SbK0kG+uv5a6RNvdg7LklSWuwWUpCXpRkqWnlkONr9BnoKkK6koZY5PdXILGo4dfRY627B2v2x19sjs/ZNeuU2h2DtXA7y23XgKrVOF3HjKbK495Y1Z/DUCmqlEsZN45AynkH37qnS29+691737r3Xvfuvde9+691//09/j37r3Xvfuvde9+691737r3Xz6P52O9sjvP+ZV8gYayZnpdmDYGycPEzs602PxPX+2ayeKIH9CzZjJ1cxA41ysfz796dX8k6qxMjlFjudK3sObcm/H5/PvfTnWMEqbj37r3XVQ7SBmYm4AHP8AgoX37r3W/h/Iv3tkd5/y3OmYcnUNUz7MzfY2yYZXJLjHYve+Zr8VTkm5K0eNy0UKf0jjUfj3rpjq3r37r3Xvfuvde9+691737r3X/9Tf49+691737r3Xvfuvde9+6918+z+dzs2o2d/Mv78mlVhS7xp+ut6Y92XSJYMn11tigqSl/wBSplsTUpf+qH+nv3l1cfAeqqPe+nOve/de6xTkqpP5+v8AvH+8Hn37r3W/1/Iz2bVbR/lr9HzVsfin3hlOyd5hLWb7XK9g7io8dI35PnxmMhkB/KsPeumOrdffuvde9+691737r3Xri9r8/W35t/W3v3Xuv//V3+Pfuvde9+691737r3Xvfuvdad//AApZ6aqsP3J8e+/qOhP8L3rsPM9X5qujQmKLObHzU24sQtWw4WoyWJ3hOsN/1JQPb9J9+6svxDrWkBuAf8P+R/7z7307137917rpKSsydZRYrHUs9dkMlV09BQUVNG0tTWVtZMkFLS08SAtLPUTyKiqOWYgD37r3X08/i91OnRHxy6N6cCKk/W3VWx9o5EoQyzZnD7eoKbOVQZeGNXmFnlJ5uX+p966Y6Hj37r3Xvfuvde9+691g0H7ryXOn7fRbm1/Jqv8A0vb37r3X/9bf3BBFxyLkf7EEgj/YEe/de679+691737r3XvfuvdES/mRfFHBfMX4idqdV1tEk27Mdha3fXVuRCBqnE9lbUxtdW7denc8pDm1ebFVXBJo6+Ww1aSPde6+b1TFgpVwQyEqysCpVlNipUgEEN9fe+n+pJFgx/1P19+691dL/Ig+KOD+RvzK/v8A70oY8nsr424Wg7M/h8yCWkyXYNRlUouu6StRgQ0GPrqaqywBNnmxcaMCjMDrpotUAefW+J791Xr3v3Xuve/de697917r3v3Xuv/X39lAAsP9Ux/27k/72ffuvdcvfuvde9+691737r3WKWWKGKSWeSOKGKN5JpZWVIo4kBaSSR3IRI0QEkk2A+vv3Xuvls9s0uCou2+06XatZTZHbFP2PviDbmQopFlo6/AxbnyceHraSRPTJTVePWOSNhwVYEce99P9ID37r3W2p/wmVg23Fs75aTR19A28KvdPVsdXi/LEMnFtqgxW72x2Q8BPmagqcpkqqPWAVEkViQSL66ab8P2dbS3v3Veve/de697917r3v3Xuve/de6//0N/j37r3XvfuvdJLd+/djde4uTOb+3ntTZGFiDNLl93bhxG28YgQXYvXZiro6UaR9fV7917qtDun+c58GOpI6ykwO/c33huSnSUQ4DpfbtXueCaZRaNTu/INhtjeF5OC8eRmYC5CG1j7r3Wv/wDNz+bP8t/lztzO9adc7Th+N/Smchnx+ehhzb5HsLeOEqEaCpxuf3TDBSx47DV8BInocdTwGVGaKaonhZlPutinnw6ofzeBocCTT/eLXVQYh3iUJChW/wCldTM31+pJ/wBb3vp7pO0vgabTOLxM3qINiAT9VItyPfuvdGz+N2/u8Pjt2Jhu4/jfv+XbO88XG1PLHqiejzWHmeKeu29uLFVCTY3P4XINAnlpqiPSHRJEKSxxyL49Ufy62dvj1/P725U0lBg/lx0Xu7rnOokcFZv3q6mbeWx6uQBRJX1W2amsTdeAgY3Pip5My39CPp7103T06uC6g+dfxA74FPH1h8hOtM7k6pYzFtzIZ+Hau7ryEWQ7R3YuD3LqDccUpFx9ffuvdGyVgwDKQysAQQbgg8ggj6g+/de679+691737r3X/9HZ/wDnl/OJ+PfwxP8AczBUs3dvdVZTST02xNq5WmosLt5WeWClqd87q8GRXEfczRkw0dNTVlbNHZ2SKKSOVvdbAJ4dUO9i/wA0X+YL8gRPWV3auL+O2yq0s9NtbqHHQ4LLR0ri8Qq965OTK7y+7EZGpqatpYy1yEX6D2OrUT16IlurP7MrslJn+xt77k7J3I2tp8xvDcWU3PlJpG9T+SvzVZXVchZhc3b37qnQb5XvfaOGjeDbeEpVZRZHESEiw4Nrfj3vp/oB91dw7i3EZI/MaeBiQEjOiym/4HHv3XugkmmlqHZ5XZmY3JJ1Hk3+p/xPv3XusX0synj/AH3B9+690oMLubK4SZJqKpkjKkGwc24I/F7e/de6MHtr5DVdNGlNm6KKtisFYyIjlhex+ov+PfuvdChTb96h3YgTK4mmpZZOS6oifWxJ4H4/w966Y6Ml1j3z3t1IIaj49fKDsvY8FPpem23/AHpqs5tAlDdUk2buRsxtaVb8eqkJt7917qyTo3+f3291Xn8VtD5ndX4ffG2KuaOn/wBK3VNNHt/c9ND5EWXIZPZ1VUvtrPyRISzxUc2IIXlFkI0e/dep6dbF3+zd/HL/AEAf7ND/AKVdt/6D/wC6/wDe7++3ml8P8M8/2P2n8M8X8X/j/wDFf8h/hvg+++//AMn8Xl9Hv3Xuv//Sqj/vTkKjJTZzIVkmUy9XXrlKvI5KSasqqmt+5aseaaaWYySNLM5LXP04Gn37q54HpRZbs/dWZGiqybxx20iOmDRIABYABne3HvdOt6Pn0jJslPUMTPUTSk/XWzNwR/Qm/Fvfur9RzOjHkkD/AABt/tr+/de64+ZP8f8Abe/de695V/2r/kk+/de678q3tzf/AFvfuvdd6x/j/vH/ABX37r3XtY/x/wB4/wCK+/de65rOVN1LAj6EXuB9eOffuvdOtDubLYyRXpMhUwsvIsxIv/rE2t7917p33Dv7Oblx9NjsvURVMNJP5oZDGwmD+N47NIzEadMhtYD37r3Tj/pd7C/0Z/6Hv70Zb/Rz/eL+9X92vup/4d/F/t/t/N4dejRb1aLadXqtfn37r3X/06bKf7HwR2/iHm9X6/t/FfUdH6Ob+O1/9q+nHvfTg1edepUWq/Nvof8AXt/j/j791cdZTq5/2P8Ar3/5F/vPv3XusP7n4/2P6vr/ALD37r3XY8n5/r/tXv3XupA1fjVb/C/v3XusTeXVxa3+P1/3n/D37r3XR+7/ABa3+N/+I9+6910PvLj9P1H9ffuvdTF1afVbVbn62vf8f4f8R7917qK3l1/i1/z/AL6309+691xbyafVa3NrfW1z9fxf+n+Pv3Xuu/3dP5/T/wAnaf8Aob37r3X/2Q==',

	// end app settings
    initComponent: function(){
        Ext.tip.QuickTipManager.init();
        var me = this;

	    me.nav = me.getController('Navigation');
	    me.cron = me.getController('Cron');

	    me.lastCardNode = null;
        me.prevNode = null;
        me.fullMode = window.innerWidth >= me.minWidthToFullMode;
        me.patient = {
            name: null,
            pid: null,
            pic: null,
            sex: null,
            dob: null,
            age: null,
            eid: null,
            readOnly: false
        };

        /**
         * Create the model/store of the AuditLog
         * @type {*}
         */
        //me.User = Ext.ModelManager.getModel('App.model.administration.AuditLog');


        /**
         * This store will handle the patient pool area
         */
        me.patientPoolStore = Ext.create('App.store.areas.PoolArea');
        /*
         * TODO: this should be managed by the language files
         * The language file has a definition for this.
         */
        if(me.currency == '$'){
            me.icoMoney = 'icoDollar';
        }else if(me.currency == '€'){
            me.icoMoney = 'icoEuro';
        }else if(me.currency == '£'){
            me.icoMoney = 'icoLibra';
        }else if(me.currency == '¥'){
            me.icoMoney = 'icoYen';
        }
        /**
         * GaiaEHR Support Page
         */
        me.winSupport = Ext.create('Ext.window.Window', {
            title: i18n('support'),
            closeAction: 'hide',
            bodyStyle: 'background-color: #ffffff; padding: 5px;',
            animateTarget: me.Footer,
            resizable: false,
            draggable: false,
            maximizable: false,
            autoScroll: true,
            maximized: true,
            dockedItems: {
                xtype: 'toolbar',
                dock: 'top',
                items: ['-', {
                    text: 'List issues',
                    iconCls: 'list',
                    action: 'http://GaiaEHR.org/projects/GaiaEHR001/issues',
                    scope: me,
                    handler: me.showMiframe
                }, '-', {
                    text: 'Create an issue',
                    iconCls: 'icoAddRecord',
                    action: 'http://GaiaEHR.org/projects/GaiaEHR001/issues/new',
                    scope: me,
                    handler: me.showMiframe
                }]
            }
        });
        /**
         * header Panel
         */
        me.Header = Ext.create('Ext.container.Container', {
            region: 'north',
            height: 44,
            split: false,
            collapsible: false,
            collapsed: true,
            frame: false,
            border: false,
            bodyStyle: 'background: transparent',
            margins: '0 0 0 0'
        });
        me.patientBtn = me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:left',
            margin: 0,
            scope: me,
            handler: me.openPatientSummary,
            tooltip: i18n('patient_btn_drag'),
            listeners: {
                scope: me,
                afterrender: me.patientBtnRender
            },
            tpl: me.patientBtnTpl()
        });
        me.patientSummaryBtn = me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:left',
            margin: '0 0 0 3',
            cls: 'headerLargeBtn',
            padding: 0,
            iconCls: 'icoPatientInfo',
            scope: me,
            handler: me.openPatientSummary,
            tooltip: i18n('patient_summary')
        });
        me.patientOpenVisitsBtn = me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:left',
            margin: '0 0 0 3',
            cls: 'headerLargeBtn',
            padding: 0,
            iconCls: 'icoBackClock',
            scope: me,
            handler: me.openPatientVisits,
            tooltip: i18n('patient_visits_history')
        });
        if(acl['add_encounters']){
            me.patientCreateEncounterBtn = me.Header.add({
                xtype: 'button',
                scale: 'large',
                style: 'float:left',
                margin: '0 0 0 3',
                cls: 'headerLargeBtn',
                padding: 0,
                iconCls: 'icoClock',
                scope: me,
                handler: me.createNewEncounter,
                tooltip: i18n('new_encounter')
            });
        }
        me.patientCloseCurrEncounterBtn = me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:left',
            margin: '0 0 0 3',
            cls: 'headerLargeBtn',
            padding: 0,
            iconCls: 'icoArrowDown',
            scope: me,
            handler: me.stowPatientRecord,
            tooltip: i18n('stow_patient_record')
        });
        me.patientCheckOutBtn = me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:left',
            margin: '0 0 0 3',
            cls: 'headerLargeBtn',
            padding: 0,
            iconCls: 'icoCheckOut',
            scope: me,
            handler: me.chargePatient,
            tooltip: i18n('visit_check_out')
        });
        me.patientChargeBtn = me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:left',
            margin: '0 0 0 3',
            cls: 'headerLargeBtn',
            padding: 0,
            iconCls: me.icoMoney,
            scope: me,
            handler: me.onPaymentEntryWindow,
            tooltip: i18n('payment_entry')
        });
        me.Header.add({
            xtype: 'panel',
            bodyPadding: '8 11 5 11',
            margin: '0 0 0 3',
            style: 'float:left',
            items: [
                {
                    xtype: 'patienlivetsearch',
                    emptyText: i18n('patient_live_search') + '...',
                    fieldStyle: me.fullMode ? 'width:300' : 'width:250',
                    listeners: {
                        scope: me,
                        select: me.liveSearchSelect,
                        blur: function(combo){
                            combo.reset();
                        }
                    }
                }
            ]
        });
        me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:left',
            margin: '0 0 0 3',
            padding: 4,
            itemId: 'patientNewReset',
            iconCls: 'icoAddPatient',
            scope: me,
            handler: me.newPatient,
            tooltip: i18n('create_a_new_patient')
        });
        me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:left',
            margin: '0 0 0 3',
            cls: 'headerLargeBtn emerBtn',
            overCls: 'emerBtnOver',
            padding: 0,
            itemId: 'createEmergency',
            iconCls: 'icoEmer',
            scope: me,
            handler: me.createEmergency,
            tooltip: i18n('create_new_emergency')
        });
        me.userSplitBtn = me.Header.add({
            xtype: 'button',
            text: me.user.title + ' ' + me.user.lname,
            scale: 'large',
            iconCls: isEmerAccess ? 'icoUnlocked32' : 'icoDoctor',
            iconAlign: 'left',
            cls: 'drButton',
            style: 'float:right',
            margin: '0 0 0 3',
            menu: [
                {
                    text: i18n('my_account'),
                    iconCls: 'icoUser',
                    handler: function(){
                        me.nav.navigateTo('App.view.miscellaneous.MyAccount');
                    }
                },
                {
                    text: i18n('my_settings'),
                    iconCls: 'icoSettings',
                    handler: function(){
                        me.nav.navigateTo('App.view.miscellaneous.MySettings');
                    }
                },
                {
                    text: i18n('logout'),
                    iconCls: 'icoLogout',
                    scope: me,
                    handler: me.appLogout
                }
            ]
        });

	    if(acl['emergency_access']){
		    me.userSplitBtn.menu.insert(0,{
			    text:i18n('emergency_access'),
			    cls: 'emergency',
			    iconCls:'icoUnlocked',
			    scope:me,
			    handler:me.onEmergencyAccessClick
		    });
	    }

        me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:right',
            margin: '0 0 0 3',
            cls: 'headerLargeBtn',
            padding: 0,
            itemId: 'patientCheckIn',
            iconCls: 'icoCheckIn',
            scope: me,
            handler: me.onPatientLog,
            tooltip: i18n('arrival_log')
        });
        me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:right',
            margin: '0 0 0 3',
            cls: 'headerLargeBtn',
            padding: 0,
            itemId: 'patientPoolArea',
            iconCls: 'icoPoolArea',
            scope: me,
            handler: me.goToPoolAreas,
            tooltip: i18n('pool_areas')
        });
        me.Header.add({
            xtype: 'button',
            scale: 'large',
            style: 'float:right',
            margin: '0 0 0 3',
            cls: 'headerLargeBtn',
            padding: 0,
            itemId: 'floorPlans',
            iconCls: 'icoZoneAreasBig',
            scope: me,
            handler: me.goToFloorPlans,
            tooltip: i18n('floor_plans')
        });
        /**
         * The panel definition for the the TreeMenu & the support button
         */
        me.navColumn = Ext.create('Ext.panel.Panel', {
            title: i18n('navigation'),
            stateId: 'navColumn',
            layout: 'border',
            region: globals['main_navigation_menu_left'],
            width: parseFloat(globals['gbl_nav_area_width']),
            split: true,
            collapsible: true,
            collapsed: false,
            items: [
                {
                    xtype: 'treepanel',
                    region: 'center',
	                action:'mainNav',
                    cls: 'nav_tree',
                    hideHeaders: true,
                    rootVisible: false,
                    border: false,
                    width: parseFloat(globals['gbl_nav_area_width']),
	                store: Ext.create('App.store.navigation.Navigation', {
		                autoLoad: true
	                })
                },
                me.patientPoolArea = Ext.create('Ext.Panel', {
                    title: i18n('patient_pool_areas'),
                    layout: 'fit',
                    region: 'south',
                    bodyPadding: 5,
                    height: 25,
                    cls: 'patient-pool',
                    split: true,
                    collapsible: true,
                    border: false,
                    //                    overflowY: 'auto',
                    items: [
                        {
                            xtype: 'dataview',
                            loadMask: false,
                            cls: 'patient-pool-view',
                            tpl: new Ext.XTemplate(
	                            '<tpl for=".">' +
                                '<div class="patient-pool-btn x-btn x-btn-default-large {priority}">' +
                                '<div class="patient_btn_img"><img src="data:image/jpg;base64,{[this.getPatientImage(values.photoSrc)]}" width="32" height="32"></div>' +
                                '<div class="patient_btn_info">' +
                                '<div class="patient-name">{shortName}</div>' +
                                '<div class="patient-name">#{pid} ({poolArea})</div>' +
                                '</div>' +
                                '</div>' +
                                '</tpl>',
	                            {
		                            getPatientImage:function(image){
										return image != '' ? image : me.patientImage;
		                            }
	                            }
                            ),
                            itemSelector: 'div.patient-pool-btn',
                            overItemCls: 'patient-over',
                            selectedItemClass: 'patient-selected',
                            singleSelect: true,
                            store: me.patientPoolStore,
                            listeners: {
                                scope: me,
                                render: me.initializeOpenEncounterDragZone
                            }
                        }
                    ]
                })
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    border: true,
                    margin: '3 0 0 0',
                    padding: 5,
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: ['-', {
                        xtype: 'button',
                        frame: true,
                        text: 'GaiaEHR Support',
                        iconCls: 'icoHelp',
                        action: 'http://gaiaehr.org/',
                        scope: me,
                        handler: me.showMiframe
                    }, '-']
                }
            ],
            listeners: {
                scope: me,
                beforecollapse: me.navCollapsed,
                beforeexpand: me.navExpanded

            }
        });
        /**
         * MainPanel is where all the pages are displayed
         */
        me.MainPanel = Ext.create('Ext.container.Container', {
            region: 'center',
            layout: 'card',
            border: true,
            itemId: 'MainPanel',
            defaults: {
                layout: 'fit',
                xtype: 'container'
            },
            listeners: {
                scope: me,
                afterrender: me.initializeOpenEncounterDropZone
            }
        });
        /**
         * General Area
         */
        me.nav['App_view_dashboard_Dashboard'] = me.MainPanel.add(Ext.create('App.view.dashboard.Dashboard'));
//        me.Calendar      = me.MainPanel.add(Ext.create('App.view.calendar.Calendar'));
//        me.Messages      = me.MainPanel.add(Ext.create('App.view.messages.Messages'));
//        me.PatientSearch = me.MainPanel.add(Ext.create('App.view.search.PatientSearch'));
        me.nav['App_view_areas_FloorPlan'] = me.MainPanel.add(Ext.create('App.view.areas.FloorPlan'));
        /**
         * Patient Area
         */
//        me.NewPatient    = me.MainPanel.add(Ext.create('App.view.patient.NewPatient'));
//	    me.Summary       = me.MainPanel.add(Ext.create('App.view.patient.Summary'));
//        me.Visits        = me.MainPanel.add(Ext.create('App.view.patient.Visits'));
//	    me['Nav_App_view_patient_Encounter'] = me.MainPanel.add(Ext.create('App.view.patient.Encounter'));
//        me.VisitCheckout = me.MainPanel.add(Ext.create('App.view.patient.VisitCheckout'));
//        /**
//         * Fees Area
//         */
//        me.MainPanel.add(Ext.create('App.view.fees.Billing'));
//        me.MainPanel.add(Ext.create('App.view.fees.Payments'));
//        /**
//         * Miscellaneous
//         */
//        me.MainPanel.add(Ext.create('App.view.miscellaneous.Addressbook'));
//        me.MainPanel.add(Ext.create('App.view.miscellaneous.MyAccount'));
//        me.MainPanel.add(Ext.create('App.view.miscellaneous.MySettings'));
//        me.MainPanel.add(Ext.create('App.view.miscellaneous.OfficeNotes'));
//        me.MainPanel.add(Ext.create('App.view.miscellaneous.Websearch'));
//
        me.nav['App_view_areas_PatientPoolDropZone'] = me.MainPanel.add(Ext.create('App.view.areas.PatientPoolDropZone'));
//
//
//        if(acl['access_gloabal_settings'])  me.MainPanel.add(Ext.create('App.view.administration.Globals'));
//        if(acl['access_facilities'])        me.MainPanel.add(Ext.create('App.view.administration.Facilities'));
//        if(acl['access_users'])             me.MainPanel.add(Ext.create('App.view.administration.Users'));
//        if(acl['access_practice'])          me.MainPanel.add(Ext.create('App.view.administration.Practice'));
//        if(acl['access_data_manager'])      me.MainPanel.add(Ext.create('App.view.administration.DataManager'));
//        if(acl['access_preventive_care'])   me.MainPanel.add(Ext.create('App.view.administration.PreventiveCare'));
////        if(acl['access_medications'])       me.MainPanel.add(Ext.create('App.view.administration.Medications'));
//        if(acl['access_floor_plans'])       me.MainPanel.add(Ext.create('App.view.administration.FloorPlans'));
//        if(acl['access_roles'])             me.MainPanel.add(Ext.create('App.view.administration.Roles'));
//        if(acl['access_layouts'])           me.MainPanel.add(Ext.create('App.view.administration.Layout'));
//        if(acl['access_lists'])             me.MainPanel.add(Ext.create('App.view.administration.Lists'));
//        if(acl['access_event_log'])         me.MainPanel.add(Ext.create('App.view.administration.Log'));
//        if(acl['access_documents'])         me.MainPanel.add(Ext.create('App.view.administration.Documents'));
//
//        me.MainPanel.add(Ext.create('App.view.administration.ExternalDataLoads'));
//        me.MainPanel.add(Ext.create('App.view.administration.Applications'));
//        me.MainPanel.add(Ext.create('App.view.administration.Modules'));
        /**
         * Footer Panel
         */
        me.Footer = Ext.create('Ext.container.Container', {
            height: me.fullMode ? 30 : 60,
            split: false,
            padding: '3 0',
            region: 'south',
            items: [
                {
                    xtype: 'dataview',
                    margin: '0 0 3 0',
                    hidden: true,
                    hideMode: 'offsets',
                    cls: 'patient-pool-view-footer x-toolbar x-toolbar-default x-box-layout-ct',
                    tpl: '<div class="x-toolbar-separator x-toolbar-item x-toolbar-separator-horizontal" style="float:left; margin-top:5px;" role="presentation" tabindex="-1"></div>' + '<tpl for=".">' + '<div class="patient-pool-btn-small x-btn x-btn-default-small {priority}" style="float:left">' + '<div class="patient_btn_info">' + '<div class="patient-name">{name} ({pid})</div>' + '</div>' + '</div>' + '<div class="x-toolbar-separator x-toolbar-item x-toolbar-separator-horizontal" style="float:left; margin-top:5px; margin-left:3px;" role="presentation" tabindex="-1"></div>' + '</tpl>',
                    itemSelector: 'div.patient-pool-btn-small',
                    overItemCls: 'patient-over',
                    selectedItemClass: 'patient-selected',
                    singleSelect: true,
                    loadMask: false,
                    store: me.patientPoolStore,
                    listeners: {
                        render: me.initializeOpenEncounterDragZone
                    }
                },
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
	                    {
		                    xtype:'activefacilitiescombo',
		                    emptyText:'Facilities',
		                    width: parseFloat(globals['gbl_nav_area_width']) - 4,
		                    listeners:{
			                    scope: me,
			                    select: me.onFacilitySelect
		                    }
	                    },
	                    '-',
                        {
                            text: 'Copyright (C) 2011 GaiaEHR (Electronic Health Records) |:|  Open Source Software operating under GPLv3 |:| v' + me.version,
                            iconCls: 'icoGreen',
                            disabled: true,
                            action: 'http://GaiaEHR.org/projects/GaiaEHR001',
                            scope: me,
                            handler: me.showMiframe
                        },
                        '->',
                        {
                            text: i18n('news'),
                            action: 'http://GaiaEHR.org/projects/GaiaEHR001/news',
                            scope: me,
                            handler: me.showMiframe
                        },
                        '-',
                        {
                            text: i18n('wiki'),
                            action: 'http://gaiaehr.org/',
                            scope: me,
                            handler: me.showMiframe
                        },
                        '-',
                        {
                            text: i18n('issues'),
                            action: 'http://gaiaehr.org/',
                            scope: me,
                            handler: me.showMiframe
                        },
                        '-',
                        {
                            text: i18n('forums'),
                            action: 'http://gaiaehr.org/',
                            scope: me,
                            handler: me.showMiframe
                        },
                        '-',
                        {
                            text: '<span style="color: red">'+i18n('FACTORY RESET')+'</span>',
                            scope: me,
                            handler: me.resetApp
                        }
                    ]
                }
            ]
        });

	    me.FacilityCmb = me.Footer.query('activefacilitiescombo')[0];
		me.FacilityCmb.getStore().on('load', me.onFacilityComboLoad, me);


        me.MedicalWindow = Ext.create('App.view.patient.windows.Medical');
        me.ChartsWindow = Ext.create('App.view.patient.windows.Charts');
        me.PaymentEntryWindow = Ext.create('App.view.fees.PaymentEntryWindow');
        me.PreventiveCareWindow = Ext.create('App.view.patient.windows.PreventiveCare');
        me.NewDocumentsWindow = Ext.create('App.view.patient.windows.NewDocuments');
        me.DocumentViewerWindow = Ext.create('App.view.patient.windows.DocumentViewer');
        me.newEncounterWindow = Ext.create('App.view.patient.windows.NewEncounter');

        if(acl['access_encounter_checkout']){
            me.checkoutWindow = Ext.create('App.view.patient.windows.EncounterCheckOut');
        }

        me.layout = {
            type: 'border',
            padding: 3
        };
        me.defaults = {
            split: true
        };
        me.items = [me.Header, me.navColumn, me.MainPanel, me.Footer];
        me.listeners = {
            render: me.appRender,
            beforerender: me.beforeAppRender
        };
        me.callParent(arguments);
        me.signature = Ext.create('App.view.signature.SignatureWindow');

    },

	getController:function(controller){
		return App.Current.getController(controller);
	},

	onFacilitySelect:function(cmb, records){
		var me = this;

		Facilities.setFacility(records[0].data.option_value, function(provider, response){

			if(records[0].data.option_value == response.result){

				me.msg(i18n('sweet'), i18n('facility') + ' ' + records[0].data.option_name);
				me.setWindowTitle(records[0].data.option_name);
				me.nav['App_view_areas_PatientPoolDropZone'].reRenderPoolAreas();
				me.nav['App_view_areas_FloorPlan'].renderZones();
				me.getPatientsInPoolArea();

			}
		});



	},

	onFacilityComboLoad:function(store, records){
		var rec = store.findRecord('option_value', this.user.facility);
		this.FacilityCmb.setValue(rec);
		this.setWindowTitle(rec.data.option_name)
	},

	setWindowTitle:function(facility){
		window.document.title = 'GaiaEHR :: ' + facility;
	},

    /**
     * AuditLog('Data created');
     * Function to inject logs to the audit log table
     * This function should be used on every screen that display
     * health information of patient.
     * Event: create, read, update, delete
     */
    AuditLog: function(message){
        var log = Ext.create('App.model.administration.AuditLog',{
            eid: this.patient.eid,
            patient_id: this.patient.pid,
            event:message
        }).save({
           callback:function(){
               delete log;
           }
        });
    },

    /**
     * Show the medical window dialog.
     */
    onMedicalWin: function(btn){
        this.MedicalWindow.show();
        this.MedicalWindow.down('toolbar').getComponent(btn.action).toggle(true);
        this.MedicalWindow.cardSwitch(btn);
    },

    /**
     * Show the Charts window dialog.
     */
    onChartsWin: function(){
        this.ChartsWindow.show();
    },

    /**
     * Show the Document window dialog.
     */
    onNewDocumentsWin: function(action){
        this.NewDocumentsWindow.eid = this.patient.eid;
        this.NewDocumentsWindow.pid = this.patient.pid;
        this.NewDocumentsWindow.show();
        this.NewDocumentsWindow.cardSwitch(action);
    },

    onWebCamComplete: function(msg){
        var panel = this.getActivePanel();
        if(panel.id == 'panelSummary'){
            panel.demographics.completePhotoId();
        }
        this.msg('Sweet!', i18n('patient_image_saved'));
    },

	onPatientLog: function(){
        if(this.patientArrivalLog){
            this.patientArrivalLog.show();
        }else{
            this.patientArrivalLog = Ext.create('App.view.patient.windows.ArrivalLog').show();
        }
    },

    /**
     * Show the Payment Entry window dialog.
     */
    onPaymentEntryWindow: function(){
        this.PaymentEntryWindow.show();
    },

    /**
     * Show the new patient form panel.
     */
    newPatient: function(){
        this.nav.navigateTo('App.view.patient.NewPatient');
    },

	//*****************************************************************
	//** EMERGENCY STUFF **********************************************
	//*****************************************************************

	createEmergency: function(){
        var me = this, emergency;
        Ext.Msg.show({
            title: i18n('wait') + '!!!',
            msg: i18n('are_you_sure_you_want_to_create_a_new') + ' <span style="color: red">"' + i18n('emergency') + '"</span>?',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.WARNING,
            fn: function(btn){
                if(btn == 'yes'){
                    Emergency.createNewEmergency(function(provider, response){
                        emergency = response.result.emergency;
                        if(response.result.success){

                            me.setPatient(emergency.pid, emergency.eid, function(){
                                me.openEncounter(emergency.eid);
                            });
                            me.msg('Sweet!', emergency.name + ' ' + i18n('created'))
                        }
                    });
                }
            }
        });
    },

	onEmergencyAccessClick:function(){
		var me = this;
		Ext.Msg.show({
			title:i18n('wait'),
			msg: i18n('emergency_access_question') + '<br>' + i18n('emergency_access_disclaimer'),
			buttons: Ext.Msg.YESNO,
			icon: Ext.Msg.QUESTION,
			fn: function(btn){
				if(btn == 'yes') me.doEmergencyAccess();
			}
		});
	},

	doEmergencyAccess:function(){
		ACL.emergencyAccess(app.user.id, function(success){
			if(success){
				window.location = './';
				return;
			}
			Ext.Msg.alert(i18n('oops'), i18n('emergency_access_error'));
		});
	},

	//*****************************************************************


	/*
	 * Show the Create New Encounter panel.
	 */
    createNewEncounter: function(){
        var me = this;
        if(acl['access_encounters'] && acl['add_encounters']){
            me.newEncounterWindow.show();
        }else{
            me.accessDenied();
        }
    },

	openPatientSummary: function(){
        var me = this;

        me.nav.navigateTo('App.view.patient.Summary', function(success){
	        if(success){
		        Ext.Function.defer(function() {
			        me.nav.getPanelByCls('App.view.patient.Summary').onActive();
		        }, 100);
	        }
        });
    },

	stowPatientRecord: function(){
        this.unsetPatient(null, true);
        this.nav.navigateTo('App.view.dashboard.Dashboard');
    },

	openEncounter: function(eid){
        var me = this;
        if(acl['access_encounters']){
            app.patient.eid = eid;
            me.nav.navigateTo('App.view.patient.Encounter', function(success){
                if(success){
	                Ext.Function.defer(function() {
		                me.nav.getPanelByCls('App.view.patient.Encounter').openEncounter(eid);
	                }, 100);
                }
            });
        }else{
            me.accessDenied();
        }
    },

	checkOutPatient: function(eid){
        this.nav.navigateTo('App.view.patient.VisitCheckout');
    },

	chargePatient: function(){
        this.nav.navigateTo('panelVisitPayment');
    },

	openPatientVisits: function(){
        this.nav.navigateTo('App.view.patient.Visits');
    },

	goToPoolAreas: function(){
        this.nav.navigateTo('App.view.areas.PatientPoolDropZone');
    },

	goToFloorPlans: function(){
        this.nav.navigateTo('App.view.areas.FloorPlan');
    },


    navCollapsed: function(){
        var me = this, navView = me.patientPoolArea, foot = me.Footer, footView;
        if(foot){
            footView = foot.down('dataview');
            foot.setHeight(60);
            footView.show();
        }
        me.navColumn.isCollapsed = true;
        navView.hide();
    },

	navExpanded: function(){
        var me = this, navView = me.patientPoolArea, foot = me.Footer, footView;
        if(foot){
            footView = foot.down('dataview');
            foot.setHeight(30);
            footView.hide();
        }
        me.navColumn.isCollapsed = false;
        navView.show();
    },

    /**
     * Function to get the current active panel.
     * NOTE: This may be used on all the application.
     */
    getActivePanel: function(){
        return this.MainPanel.getLayout().getActiveItem();
    },

    liveSearchSelect: function(combo, selection){
        var me = this, post = selection[0];
        if(post){
            me.setPatient(post.get('pid'), null, function(){
	            combo.reset();
                me.openPatientSummary();
            });
        }
    },

    setPatient: function(pid, eid, callback){
        var me = this;
        me.unsetPatient(function(){
            Patient.getPatientSetDataByPid(pid, function(provider, response){
                var data = response.result, msg1, msg2;
                if(data.readOnly){
                    msg1 = data.user + ' ' + i18n('is_currently_working_with') + ' "' + data.patient.name + '" ' + i18n('in') + ' "' + data.area + '" ' + i18n('area') + '.<br>' + i18n('override_read_mode_will_remove_the_patient_from_previous_user') + '.<br>' + i18n('do_you_would_like_to_override_read_mode');
                    msg2 = data.user + ' ' + i18n('is_currently_working_with') + ' "' + data.patient.name + '" ' + i18n('in') + ' "' + data.area + '" ' + i18n('area') + '.<br>';
                    Ext.Msg.show({
                            title: i18n('wait') + '!!!',
                            msg: data.overrideReadOnly ? msg1 : msg2,
                            buttons: data.overrideReadOnly ? Ext.Msg.YESNO : Ext.Msg.OK,
                            icon: Ext.MessageBox.WARNING,
                            fn: function(btn){
                                continueSettingPatient(btn != 'yes');
                            }
                        });
                }else{
                    continueSettingPatient(false);
                }
                function continueSettingPatient(readOnly){
                    me.patient = {
                        pid: data.patient.pid,
                        name: data.patient.name,
                        pic: data.patient.pic,
                        sex: data.patient.sex,
                        dob: data.patient.dob,
                        age: data.patient.age,
                        eid: eid,
                        priority: data.patient.priority,
                        readOnly: readOnly,
	                    rating: data.patient.rating
                    };
	                var panels = me.MainPanel.items.items;
	                for(var i=0; i<panels.length; i++) if(panels[i].pageRankingDiv) panels[i].pageRankingDiv.setValue(me.patient.rating);
                    me.patientButtonSet(me.patient);
                    if(me.patientSummaryBtn) me.patientSummaryBtn.enable();
                    if(me.patientOpenVisitsBtn) me.patientOpenVisitsBtn.enable();
                    if(me.patientCreateEncounterBtn) me.patientCreateEncounterBtn.enable();
                    if(me.patientCloseCurrEncounterBtn) me.patientCloseCurrEncounterBtn.enable();
                    if(me.patientChargeBtn) me.patientChargeBtn.enable();
                    if(me.patientCheckOutBtn) me.patientCheckOutBtn.enable();
                    if(typeof callback == 'function') callback(me.patient);
                }
            },true);
        });
    },

    unsetPatient: function(callback, sendRequest){
        var me = this;
	    if(sendRequest) Patient.unsetPatient(me.patient.pid);
	    me.currEncounterId = null;
	    me.patient = {
		    pid: null,
		    name: null,
		    pic: null,
		    sex: null,
		    dob: null,
		    age: null,
		    eid: null,
		    priority: null,
		    readOnly: false,
		    rating: null
	    };
	    me.patientButtonRemoveCls();
	    if(typeof callback == 'function'){
		    callback(true);
	    }else{
		    var panels = me.MainPanel.items.items;
		    for(var i=0; i<panels.length; i++) if(panels[i].pageRankingDiv) panels[i].pageRankingDiv.setValue(0);
		    if(me.patientCreateEncounterBtn) me.patientCreateEncounterBtn.disable();
		    if(me.patientSummaryBtn) me.patientSummaryBtn.disable();
		    if(me.patientOpenVisitsBtn) me.patientOpenVisitsBtn.disable();
		    if(me.patientCloseCurrEncounterBtn) me.patientCloseCurrEncounterBtn.disable();
		    if(me.patientChargeBtn) me.patientChargeBtn.disable();
		    if(me.patientCheckOutBtn) me.patientCheckOutBtn.disable();
		    me.patientButtonSet();
	    }
    },

    patientButtonSet: function(data){
        var me = this,
            patient = data || {};

        me.patientBtn.update({
            pid: patient.pid || 'record number',
	        pic: patient.pic || me.patientImage,
            name: patient.name || i18n('no_patient_selected')
        });

	    me.patientButtonRemoveCls();
        if(patient.priority) me.patientBtn.addCls(data.priority);
        me.patientBtn.setDisabled(!patient.pid);
    },

    patientButtonRemoveCls: function(){
        var me = this;
        me.patientBtn.removeCls('Minimal');
        me.patientBtn.removeCls('Delayed');
        me.patientBtn.removeCls('Immediate');
        me.patientBtn.removeCls('Expectant');
        me.patientBtn.removeCls('Deceased');
    },

    showMiframe: function(btn){
        var me = this, src = btn.action;
        me.winSupport.remove(me.miframe);
        me.winSupport.add(me.miframe = Ext.create('App.ux.ManagedIframe', {
                src: src
            }));
        me.winSupport.show();
    },

    msg: function(title, format, error, persistent) {
        var msgBgCls = (error === true) ? 'msg-red' : 'msg-green';
        this.msgCt = Ext.get('msg-div');
        this.msgCt.alignTo(document, 't-t');
        var s = Ext.String.format.apply(String, Array.prototype.slice.call(arguments, 1)),
            m = Ext.core.DomHelper.append(this.msgCt, {
                html: '<div class="flyMsg ' + msgBgCls + '"><h3>' + (title || '') + '</h3><p>' + s + '</p></div>'
            }, true);
        if (persistent === true) return m; // if persitent return the message element without the fade animation
        m.addCls('fadeded');
        Ext.create('Ext.fx.Animator', {
            target: m,
            duration: error ? 7000 : 2000,
            keyframes: {
                0: { opacity: 0 },
                20: { opacity: 1 },
                80: { opacity: 1 },
                100: { opacity: 0, height: 0 }
            },
            listeners: {
                afteranimate: function() {
                    m.destroy();
                }
            }
        });
        return true;
    },

    patientBtnTpl: function(){
        return Ext.create('Ext.XTemplate',
            '<div class="patient_btn  {priority}">',
            '   <div class="patient_btn_img">' +
            '       <img src="data:image/jpg;base64,{pic}" width="32" height="32">' +
            '   </div>',
            '   <div class="patient_btn_info">',
            '       <div class="patient_btn_name">{name}</div>',
            '       <div class="patient_btn_record">( {pid} )</div>',
            '   </div>',
            '</div>');
    },

    patientBtnRender: function(btn){
        this.patientButtonSet();
        this.initializePatientPoolDragZone(btn)
    },

    getPatientsInPoolArea: function(){
        var me = this,
	        poolArea = me.patientPoolArea,
	        height = 35;

	    this.patientPoolStore.load({
            extraPrams:{ uid:me.user.id },
            callback: function(records){

	            if(records.length >= 1){
                    for(var i = 0; i < records.length; i++){
                        height = height + 45;
                    }
                }else{
                    height = 25;
                }

                if(me.navColumn.collapsed === false && !me.navColumn.isCollapsingOrExpanding){
                    height = (height > 300) ? 300 : height;
                    poolArea.down('dataview').refresh();
                    poolArea.setHeight(height);
                }
            }
        });
	    me.nav['App_view_areas_PatientPoolDropZone'].reloadStores();
    },



    initializePatientPoolDragZone: function(panel){
        panel.dragZone = Ext.create('Ext.dd.DragZone', panel.getEl(), {
            ddGroup: 'patientPoolAreas',
            getDragData: function(){
	            if(app.patient.pid){
                    var sourceEl = app.patientBtn.el.dom,
	                    d;

                    if(sourceEl){
                        d = sourceEl.cloneNode(true);
                        d.id = Ext.id();
                        return panel.dragData = {
                            copy: true,
                            sourceEl: sourceEl,
                            repairXY: Ext.fly(sourceEl).getXY(),
                            ddel: d,
                            records: [panel.data],
                            patient: true
                        };
                    }

                    return false;
                }

                return false;
            },

            getRepairXY: function(){
                app.nav.goBack();
                return this.dragData.repairXY;
            },

	        onBeforeDrag:function(){
		        app.goToPoolAreas();
            }
        });
    },

    /**
     *
     * @param panel
     */
    initializeOpenEncounterDragZone: function(panel){
        panel.dragZone = Ext.create('Ext.dd.DragZone', panel.getEl(), {
            ddGroup: 'patient',
            newGroupReset: true,
            b4MouseDown: function(e){
                if(this.newGroupReset){
                    var sourceEl = e.getTarget(panel.itemSelector, 10), patientData = panel.getRecord(sourceEl).data;
                    this.removeFromGroup(this.ddGroup);
//                    say('drag record:');
//                    say(patientData);
                    if(patientData.floorPlanId != 0 && patientData.patientZoneId == 0){
                        app.nav.navigateTo('App.view.areas.FloorPlan');
                        this.ddGroup = 'patientPoolAreas';
                    }else{
                        this.ddGroup = 'patient';
                        app.MainPanel.el.mask(i18n('drop_here_to_open') + ' <strong>"' + panel.getRecord(sourceEl).data.name + '"</strong> ' + i18n('current_encounter'));
                    }
                    this.addToGroup(this.ddGroup);
                    this.newGroupReset = false;
                }
                this.autoOffset(e.getPageX(), e.getPageY());
            },
            endDrag: function(e){
                this.newGroupReset = true;
            },
            getDragData: function(e){
                var sourceEl = e.getTarget(panel.itemSelector, 10), d, patientData = panel.getRecord(sourceEl).data;
                if(sourceEl){
                    d = sourceEl.cloneNode(true);
                    d.id = Ext.id();
                    return panel.dragData = {
                        sourceEl: sourceEl,
                        repairXY: Ext.fly(sourceEl).getXY(),
                        ddel: d,
                        patientData: patientData
                    };
                }
                return false;
            },
            getRepairXY: function(){
                app.MainPanel.el.unmask();
                this.newGroupReset = true;
                return this.dragData.repairXY;
            }
        });
    },

    onDocumentView: function(docId){
        var me = this;
        if(me.documentViewWindow) me.DocumentViewerWindow.remove(me.documentViewWindow);
        me.DocumentViewerWindow.add(
	        me.documentViewWindow = Ext.create('App.ux.ManagedIframe', {
                src: 'dataProvider/DocumentViewer.php?doc='+docId
            })
        );
        me.DocumentViewerWindow.show();
    },

    /**
     *
     * @param panel
     */
    initializeOpenEncounterDropZone: function(panel){
        var me = this;
        panel.dropZone = Ext.create('Ext.dd.DropZone', panel.getEl(), {
            ddGroup: 'patient',

            notifyOver: function(dd, e, data){
                return Ext.dd.DropZone.prototype.dropAllowed;
            },

            notifyDrop: function(dd, e, data){
                say('drop record');
                say(data.patientData);
                app.MainPanel.el.unmask();

	            if(data.patientData.eid && data.patientData.poolArea == 'Check Out'){
//		            me.VisitCheckout.el.mask(i18n('loading...'));
	            }else if(data.patientData.eid && acl['access_encounters']){
//		            me.Encounter.el.mask(i18n('loading...'));
	            }else if(data.patientData.floorPlanId == null || data.patientData.floorPlanId == 0){
//		            me.Summary.el.mask(i18n('loading...'));
	            }

	            me.setPatient(data.patientData.pid, data.patientData.eid, function(){
                    // if encounter id is set and pool area is check out....  go to Patient Checkout panel
                    if(data.patientData.eid && data.patientData.poolArea == 'Check Out'){

	                    say('checkOutPatient');
                        me.checkOutPatient(data.patientData.eid);

                    // if encounter id is set and and user has access to encounter area... go to Encounter panel
                    // and open the encounter
                    }else if(data.patientData.eid && acl['access_encounters']){

	                    say('openEncounter');
                        me.openEncounter(data.patientData.eid);
                    // else go to patient summary
                    }else{

	                    say('openEncounter');
                        me.openPatientSummary();
                    }
                });
            }
        });
    },

	/**
     * When the application finishes loading all the GaiaEHR core.
     * Then it will load all the modules.
     */
    appRender: function(){
        this.loadModules();
    },

    /**
     * Load all the modules on the modules folder.
     * This folder will hold modules created by third-party.
     */
    loadModules: function(){
        say('*** Loading Modules ***');
        Modules.getEnabledModules(function(provider, response){
            var modules = response.result;
            for(var i = 0; i < modules.length; i++){
                var m = App.Current.getController('Modules.' + modules[i].dir + '.Main');
                m.init();
                say('Module ' + modules[i].dir + ' loaded...');
            }
        });
    },

    removeAppMask: function(){
        Ext.get('mainapp-loading').remove();
        Ext.get('mainapp-loading-mask').fadeOut({
            remove: true
        });
    },

    beforeAppRender: function(){

    },

    getCurrPatient: function(){
        return this.patient.pid;
    },

    getApp: function(){
        return this;
    },

    /**
     * Access denied massage.
     */
    accessDenied: function(){
        Ext.Msg.show({
            title: 'Oops!',
            msg: i18n('access_denied'),
            buttons: Ext.Msg.OK,
            icon: Ext.Msg.ERROR
        });
    },

    alert: function(msg, icon){
        if(icon == 'error'){
            icon = Ext.Msg.ERROR
        }else if(icon == 'warning'){
            icon = Ext.Msg.WARNING
        }else if(icon == 'question'){
            icon = Ext.Msg.QUESTION
        }else{
            icon = Ext.Msg.INFO
        }
        Ext.Msg.show({
            msg: msg,
            buttons: Ext.Msg.OK,
            icon: icon,
	        minWidth :700,
            maxWidth:1000
        });
    },

    resetApp:function(){
	    Ext.Msg.show({
		    title:'WAIT!!! FOR DEBUG ONLY',
		    msg: 'This will erase all patients and related data. Do you want to continue?',
		    buttons: Ext.Msg.YESNO,
		    icon: Ext.Msg.QUESTION,
		    fn:function(btn){
				if(btn == 'yes'){
					Ext.Ajax.request({
						url: 'sql/factoryReset.php',
						success: function(response){
							alert(response.responseText);
						}
					});
				}
		    }
	    });
    }

});
