<?php
/**
 * Matcha::connect microORM v0.0.1
 * This set of classes will help Sencha ExtJS and PHP developers deliver fast and powerful application fast and easy to develop.
 * If Sencha ExtJS is a GUI Framework of the future, think Matcha micrORM as the bridge between the Client-Server
 * GAP. 
 * 
 * Matcha will read and parse a Sencha Model .js file and then connect to the database and produce a compatible database-table
 * from your model. Also will provide the basic functions for the CRUD. If you are familiar with Sencha ExtJS, and know 
 * about Sencha Models, you will need this PHP Class. You can use it in any way you want, in MVC like pattern, your own pattern, 
 * or just playing simple. It's compatible with all your coding style. 
 * 
 * Taking some ideas from diferent microORM's and full featured ORM's we bring you this cool Class. 
 * 
 * History:
 * Born in the fields of GaiaEHR we needed a way to develop the application more faster, Gino Rivera suggested the use of an
 * microORM for fast development and the development began. We tried to use some already developed and well known ORM's on the 
 * space of PHP, but none satisfied our needs. So Gino Rivera sugested the development of our own microORM (a long way to run).
 * 
 * But despite the long run, it returned to be more logical to get ideas from the well known ORM's and how Sensha manage their models
 * so this is the result. 
 *  
 */
 
class MatchaErrorHandler extends Matcha
{
	
	public $__logFile;
	
	/**
	 * function __errorProcess($errorException):
	 * Handle the error of an exception
	 * TODO: It could be more elaborated and handle other things.
	 * for example log file for GaiaEHR.
	 */
	static public function __errorProcess($errorException)
	{
		error_log('Matcha::connect microORM: ' . $errorException->getMessage() );
		return $errorException;
	}

	/**
	 * function __errorLogFile:
	 * A file that MatchaErrorHandler will put all the errors 
	 * events generated by Matcha::connect
	 */
	static public function __errorLogFile($file = NULL)
	{
		$__logFile = $file;
	}
}
