/*
 * File: app/model/UserModel.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.model.UserModel', {
    extend: 'Ext.ux.MatchaModel',

    requires: [
        'Ext.ux.MatchaField'
    ],

    table: {
        name: 'users',
        comment: 'This is a table comment'
    },

    fields: [
        {
            xtype: 'matchafield',
            name: 'id',
            type: 'int'
        },
        {
            xtype: 'matchafield',
            name: 'fullname',
            type: 'string',
            len: 80
        },
        {
            xtype: 'matchafield',
            dateFormat: 'Y-m-d H:i:s',
            name: 'dob',
            type: 'date'
        },
        {
            xtype: 'matchafield',
            name: 'email',
            type: 'string',
            len: 40
        },
        {
            xtype: 'matchafield',
            name: 'active',
            type: 'bool'
        }
    ]
});